//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CHART {
    
    private TRACK tRACKField;
    
    private RACE[] rACEField;
    
    private System.DateTime rACE_DATEField;
    
    /// <remarks/>
    public TRACK TRACK {
        get {
            return this.tRACKField;
        }
        set {
            this.tRACKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RACE")]
    public RACE[] RACE {
        get {
            return this.rACEField;
        }
        set {
            this.rACEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime RACE_DATE {
        get {
            return this.rACE_DATEField;
        }
        set {
            this.rACE_DATEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TRACK {
    
    private string cODEField;
    
    private string nAMEField;
    
    /// <remarks/>
    public string CODE {
        get {
            return this.cODEField;
        }
        set {
            this.cODEField = value;
        }
    }
    
    /// <remarks/>
    public string NAME {
        get {
            return this.nAMEField;
        }
        set {
            this.nAMEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RACE {
    
    private string bREEDField;
    
    private string cARD_IDField;
    
    private string tYPEField;
    
    private decimal pURSEField;
    
    private string rACE_TEXTField;
    
    private string aGE_RESTRICTIONSField;
    
    private string dISTANCEField;
    
    private string dIST_UNITField;
    
    private string aBOUT_DIST_FLAGField;
    
    private string cOURSE_IDField;
    
    private string cOURSE_DESCField;
    
    private string sURFACEField;
    
    private string cLASS_RATINGField;
    
    private string tRK_CONDField;
    
    private string wEATHERField;
    
    private string sTRT_DESCField;
    
    private string pOST_TIMEField;
    
    private string dTVField;
    
    private decimal fRACTION_1Field;
    
    private decimal fRACTION_2Field;
    
    private decimal fRACTION_3Field;
    
    private decimal fRACTION_4Field;
    
    private decimal fRACTION_5Field;
    
    private decimal wIN_TIMEField;
    
    private string pACE_CALL1Field;
    
    private string pACE_CALL2Field;
    
    private string pACE_FINALField;
    
    private decimal pAR_TIMEField;
    
    private EARNING_SPLITS eARNING_SPLITSField;
    
    private WAGER[] eXOTIC_WAGERSField;
    
    private CLAIM[] cLAIMEDField;
    
    private VOIDED_CLAIM[] vOIDED_CLAIMSField;
    
    private string wIND_DIRECTIONField;
    
    private string wIND_SPEEDField;
    
    private string rUNUPDISTField;
    
    private string rAILDISTField;
    
    private decimal wPS_POOLField;
    
    private bool wPS_POOLFieldSpecified;
    
    private string fOOTNOTESField;
    
    private ENTRY[] eNTRYField;
    
    private SCRATCH[] sCRATCHField;
    
    private string nUMBERField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string BREED {
        get {
            return this.bREEDField;
        }
        set {
            this.bREEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string CARD_ID {
        get {
            return this.cARD_IDField;
        }
        set {
            this.cARD_IDField = value;
        }
    }
    
    /// <remarks/>
    public string TYPE {
        get {
            return this.tYPEField;
        }
        set {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    public decimal PURSE {
        get {
            return this.pURSEField;
        }
        set {
            this.pURSEField = value;
        }
    }
    
    /// <remarks/>
    public string RACE_TEXT {
        get {
            return this.rACE_TEXTField;
        }
        set {
            this.rACE_TEXTField = value;
        }
    }
    
    /// <remarks/>
    public string AGE_RESTRICTIONS {
        get {
            return this.aGE_RESTRICTIONSField;
        }
        set {
            this.aGE_RESTRICTIONSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string DISTANCE {
        get {
            return this.dISTANCEField;
        }
        set {
            this.dISTANCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string DIST_UNIT {
        get {
            return this.dIST_UNITField;
        }
        set {
            this.dIST_UNITField = value;
        }
    }
    
    /// <remarks/>
    public string ABOUT_DIST_FLAG {
        get {
            return this.aBOUT_DIST_FLAGField;
        }
        set {
            this.aBOUT_DIST_FLAGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string COURSE_ID {
        get {
            return this.cOURSE_IDField;
        }
        set {
            this.cOURSE_IDField = value;
        }
    }
    
    /// <remarks/>
    public string COURSE_DESC {
        get {
            return this.cOURSE_DESCField;
        }
        set {
            this.cOURSE_DESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string SURFACE {
        get {
            return this.sURFACEField;
        }
        set {
            this.sURFACEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string CLASS_RATING {
        get {
            return this.cLASS_RATINGField;
        }
        set {
            this.cLASS_RATINGField = value;
        }
    }
    
    /// <remarks/>
    public string TRK_COND {
        get {
            return this.tRK_CONDField;
        }
        set {
            this.tRK_CONDField = value;
        }
    }
    
    /// <remarks/>
    public string WEATHER {
        get {
            return this.wEATHERField;
        }
        set {
            this.wEATHERField = value;
        }
    }
    
    /// <remarks/>
    public string STRT_DESC {
        get {
            return this.sTRT_DESCField;
        }
        set {
            this.sTRT_DESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
    public string POST_TIME {
        get {
            return this.pOST_TIMEField;
        }
        set {
            this.pOST_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string DTV {
        get {
            return this.dTVField;
        }
        set {
            this.dTVField = value;
        }
    }
    
    /// <remarks/>
    public decimal FRACTION_1 {
        get {
            return this.fRACTION_1Field;
        }
        set {
            this.fRACTION_1Field = value;
        }
    }
    
    /// <remarks/>
    public decimal FRACTION_2 {
        get {
            return this.fRACTION_2Field;
        }
        set {
            this.fRACTION_2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal FRACTION_3 {
        get {
            return this.fRACTION_3Field;
        }
        set {
            this.fRACTION_3Field = value;
        }
    }
    
    /// <remarks/>
    public decimal FRACTION_4 {
        get {
            return this.fRACTION_4Field;
        }
        set {
            this.fRACTION_4Field = value;
        }
    }
    
    /// <remarks/>
    public decimal FRACTION_5 {
        get {
            return this.fRACTION_5Field;
        }
        set {
            this.fRACTION_5Field = value;
        }
    }
    
    /// <remarks/>
    public decimal WIN_TIME {
        get {
            return this.wIN_TIMEField;
        }
        set {
            this.wIN_TIMEField = value;
        }
    }
    
    /// <remarks/>
    public string PACE_CALL1 {
        get {
            return this.pACE_CALL1Field;
        }
        set {
            this.pACE_CALL1Field = value;
        }
    }
    
    /// <remarks/>
    public string PACE_CALL2 {
        get {
            return this.pACE_CALL2Field;
        }
        set {
            this.pACE_CALL2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string PACE_FINAL {
        get {
            return this.pACE_FINALField;
        }
        set {
            this.pACE_FINALField = value;
        }
    }
    
    /// <remarks/>
    public decimal PAR_TIME {
        get {
            return this.pAR_TIMEField;
        }
        set {
            this.pAR_TIMEField = value;
        }
    }
    
    /// <remarks/>
    public EARNING_SPLITS EARNING_SPLITS {
        get {
            return this.eARNING_SPLITSField;
        }
        set {
            this.eARNING_SPLITSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WAGER", IsNullable=false)]
    public WAGER[] EXOTIC_WAGERS {
        get {
            return this.eXOTIC_WAGERSField;
        }
        set {
            this.eXOTIC_WAGERSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CLAIM", IsNullable=false)]
    public CLAIM[] CLAIMED {
        get {
            return this.cLAIMEDField;
        }
        set {
            this.cLAIMEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("VOIDED_CLAIM", IsNullable=false)]
    public VOIDED_CLAIM[] VOIDED_CLAIMS {
        get {
            return this.vOIDED_CLAIMSField;
        }
        set {
            this.vOIDED_CLAIMSField = value;
        }
    }
    
    /// <remarks/>
    public string WIND_DIRECTION {
        get {
            return this.wIND_DIRECTIONField;
        }
        set {
            this.wIND_DIRECTIONField = value;
        }
    }
    
    /// <remarks/>
    public string WIND_SPEED {
        get {
            return this.wIND_SPEEDField;
        }
        set {
            this.wIND_SPEEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string RUNUPDIST {
        get {
            return this.rUNUPDISTField;
        }
        set {
            this.rUNUPDISTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string RAILDIST {
        get {
            return this.rAILDISTField;
        }
        set {
            this.rAILDISTField = value;
        }
    }
    
    /// <remarks/>
    public decimal WPS_POOL {
        get {
            return this.wPS_POOLField;
        }
        set {
            this.wPS_POOLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WPS_POOLSpecified {
        get {
            return this.wPS_POOLFieldSpecified;
        }
        set {
            this.wPS_POOLFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string FOOTNOTES {
        get {
            return this.fOOTNOTESField;
        }
        set {
            this.fOOTNOTESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ENTRY")]
    public ENTRY[] ENTRY {
        get {
            return this.eNTRYField;
        }
        set {
            this.eNTRYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SCRATCH")]
    public SCRATCH[] SCRATCH {
        get {
            return this.sCRATCHField;
        }
        set {
            this.sCRATCHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string NUMBER {
        get {
            return this.nUMBERField;
        }
        set {
            this.nUMBERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EARNING_SPLITS {
    
    private decimal sPLIT_1Field;
    
    private bool sPLIT_1FieldSpecified;
    
    private decimal sPLIT_2Field;
    
    private bool sPLIT_2FieldSpecified;
    
    private decimal sPLIT_3Field;
    
    private bool sPLIT_3FieldSpecified;
    
    private decimal sPLIT_4Field;
    
    private bool sPLIT_4FieldSpecified;
    
    private decimal sPLIT_5Field;
    
    private bool sPLIT_5FieldSpecified;
    
    private decimal sPLIT_6Field;
    
    private bool sPLIT_6FieldSpecified;
    
    private decimal sPLIT_7Field;
    
    private bool sPLIT_7FieldSpecified;
    
    private decimal sPLIT_8Field;
    
    private bool sPLIT_8FieldSpecified;
    
    private decimal sPLIT_9Field;
    
    private bool sPLIT_9FieldSpecified;
    
    private decimal sPLIT_10Field;
    
    private bool sPLIT_10FieldSpecified;
    
    /// <remarks/>
    public decimal SPLIT_1 {
        get {
            return this.sPLIT_1Field;
        }
        set {
            this.sPLIT_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_1Specified {
        get {
            return this.sPLIT_1FieldSpecified;
        }
        set {
            this.sPLIT_1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_2 {
        get {
            return this.sPLIT_2Field;
        }
        set {
            this.sPLIT_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_2Specified {
        get {
            return this.sPLIT_2FieldSpecified;
        }
        set {
            this.sPLIT_2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_3 {
        get {
            return this.sPLIT_3Field;
        }
        set {
            this.sPLIT_3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_3Specified {
        get {
            return this.sPLIT_3FieldSpecified;
        }
        set {
            this.sPLIT_3FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_4 {
        get {
            return this.sPLIT_4Field;
        }
        set {
            this.sPLIT_4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_4Specified {
        get {
            return this.sPLIT_4FieldSpecified;
        }
        set {
            this.sPLIT_4FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_5 {
        get {
            return this.sPLIT_5Field;
        }
        set {
            this.sPLIT_5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_5Specified {
        get {
            return this.sPLIT_5FieldSpecified;
        }
        set {
            this.sPLIT_5FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_6 {
        get {
            return this.sPLIT_6Field;
        }
        set {
            this.sPLIT_6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_6Specified {
        get {
            return this.sPLIT_6FieldSpecified;
        }
        set {
            this.sPLIT_6FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_7 {
        get {
            return this.sPLIT_7Field;
        }
        set {
            this.sPLIT_7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_7Specified {
        get {
            return this.sPLIT_7FieldSpecified;
        }
        set {
            this.sPLIT_7FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_8 {
        get {
            return this.sPLIT_8Field;
        }
        set {
            this.sPLIT_8Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_8Specified {
        get {
            return this.sPLIT_8FieldSpecified;
        }
        set {
            this.sPLIT_8FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_9 {
        get {
            return this.sPLIT_9Field;
        }
        set {
            this.sPLIT_9Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_9Specified {
        get {
            return this.sPLIT_9FieldSpecified;
        }
        set {
            this.sPLIT_9FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal SPLIT_10 {
        get {
            return this.sPLIT_10Field;
        }
        set {
            this.sPLIT_10Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SPLIT_10Specified {
        get {
            return this.sPLIT_10FieldSpecified;
        }
        set {
            this.sPLIT_10FieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class WAGER {
    
    private string wAGER_TYPEField;
    
    private decimal nUM_TICKETSField;
    
    private decimal pOOL_TOTALField;
    
    private string wINNERSField;
    
    private decimal pAYOFFField;
    
    private string nUMBERField;
    
    /// <remarks/>
    public string WAGER_TYPE {
        get {
            return this.wAGER_TYPEField;
        }
        set {
            this.wAGER_TYPEField = value;
        }
    }
    
    /// <remarks/>
    public decimal NUM_TICKETS {
        get {
            return this.nUM_TICKETSField;
        }
        set {
            this.nUM_TICKETSField = value;
        }
    }
    
    /// <remarks/>
    public decimal POOL_TOTAL {
        get {
            return this.pOOL_TOTALField;
        }
        set {
            this.pOOL_TOTALField = value;
        }
    }
    
    /// <remarks/>
    public string WINNERS {
        get {
            return this.wINNERSField;
        }
        set {
            this.wINNERSField = value;
        }
    }
    
    /// <remarks/>
    public decimal PAYOFF {
        get {
            return this.pAYOFFField;
        }
        set {
            this.pAYOFFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string NUMBER {
        get {
            return this.nUMBERField;
        }
        set {
            this.nUMBERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CLAIM {
    
    private string hORSEField;
    
    private decimal pRICEField;
    
    private string oWNERField;
    
    private TRAINER tRAINERField;
    
    private string nUMBERField;
    
    /// <remarks/>
    public string HORSE {
        get {
            return this.hORSEField;
        }
        set {
            this.hORSEField = value;
        }
    }
    
    /// <remarks/>
    public decimal PRICE {
        get {
            return this.pRICEField;
        }
        set {
            this.pRICEField = value;
        }
    }
    
    /// <remarks/>
    public string OWNER {
        get {
            return this.oWNERField;
        }
        set {
            this.oWNERField = value;
        }
    }
    
    /// <remarks/>
    public TRAINER TRAINER {
        get {
            return this.tRAINERField;
        }
        set {
            this.tRAINERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string NUMBER {
        get {
            return this.nUMBERField;
        }
        set {
            this.nUMBERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TRAINER {
    
    private string fIRST_NAMEField;
    
    private string lAST_NAMEField;
    
    private string mIDDLE_NAMEField;
    
    private string sUFFIXField;
    
    private string kEYField;
    
    private string tYPEField;
    
    /// <remarks/>
    public string FIRST_NAME {
        get {
            return this.fIRST_NAMEField;
        }
        set {
            this.fIRST_NAMEField = value;
        }
    }
    
    /// <remarks/>
    public string LAST_NAME {
        get {
            return this.lAST_NAMEField;
        }
        set {
            this.lAST_NAMEField = value;
        }
    }
    
    /// <remarks/>
    public string MIDDLE_NAME {
        get {
            return this.mIDDLE_NAMEField;
        }
        set {
            this.mIDDLE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    public string SUFFIX {
        get {
            return this.sUFFIXField;
        }
        set {
            this.sUFFIXField = value;
        }
    }
    
    /// <remarks/>
    public string KEY {
        get {
            return this.kEYField;
        }
        set {
            this.kEYField = value;
        }
    }
    
    /// <remarks/>
    public string TYPE {
        get {
            return this.tYPEField;
        }
        set {
            this.tYPEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class VOIDED_CLAIM {
    
    private string hORSEField;
    
    private string rEASONField;
    
    private string nUMBERField;
    
    /// <remarks/>
    public string HORSE {
        get {
            return this.hORSEField;
        }
        set {
            this.hORSEField = value;
        }
    }
    
    /// <remarks/>
    public string REASON {
        get {
            return this.rEASONField;
        }
        set {
            this.rEASONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string NUMBER {
        get {
            return this.nUMBERField;
        }
        set {
            this.nUMBERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ENTRY {
    
    private string nAMEField;
    
    private string dH_DQ_FLAGSField;
    
    private string bREEDField;
    
    private LAST_PP lAST_PPField;
    
    private string wEIGHTField;
    
    private string aGEField;
    
    private SEX sEXField;
    
    private string mEDSField;
    
    private string eQUIPField;
    
    private decimal dOLLAR_ODDSField;
    
    private string pROGRAM_NUMField;
    
    private string pOST_POSField;
    
    private decimal cLAIM_PRICEField;
    
    private string sTART_POSITIONField;
    
    private POINT_OF_CALL[] pOINT_OF_CALLField;
    
    private string oFFICIAL_FINField;
    
    private string fINISH_TIMEField;
    
    private string sPEED_RATINGField;
    
    private JOCKEY jOCKEYField;
    
    private TRAINER tRAINERField;
    
    private string oWNERField;
    
    private string cOMMENTField;
    
    private WINNERS_DETAILS wINNERS_DETAILSField;
    
    private decimal wIN_PAYOFFField;
    
    private decimal pLACE_PAYOFFField;
    
    private decimal sHOW_PAYOFFField;
    
    private decimal sHOW_PAYOFF2Field;
    
    private string aXCISKEYField;
    
    /// <remarks/>
    public string NAME {
        get {
            return this.nAMEField;
        }
        set {
            this.nAMEField = value;
        }
    }
    
    /// <remarks/>
    public string DH_DQ_FLAGS {
        get {
            return this.dH_DQ_FLAGSField;
        }
        set {
            this.dH_DQ_FLAGSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string BREED {
        get {
            return this.bREEDField;
        }
        set {
            this.bREEDField = value;
        }
    }
    
    /// <remarks/>
    public LAST_PP LAST_PP {
        get {
            return this.lAST_PPField;
        }
        set {
            this.lAST_PPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string WEIGHT {
        get {
            return this.wEIGHTField;
        }
        set {
            this.wEIGHTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string AGE {
        get {
            return this.aGEField;
        }
        set {
            this.aGEField = value;
        }
    }
    
    /// <remarks/>
    public SEX SEX {
        get {
            return this.sEXField;
        }
        set {
            this.sEXField = value;
        }
    }
    
    /// <remarks/>
    public string MEDS {
        get {
            return this.mEDSField;
        }
        set {
            this.mEDSField = value;
        }
    }
    
    /// <remarks/>
    public string EQUIP {
        get {
            return this.eQUIPField;
        }
        set {
            this.eQUIPField = value;
        }
    }
    
    /// <remarks/>
    public decimal DOLLAR_ODDS {
        get {
            return this.dOLLAR_ODDSField;
        }
        set {
            this.dOLLAR_ODDSField = value;
        }
    }
    
    /// <remarks/>
    public string PROGRAM_NUM {
        get {
            return this.pROGRAM_NUMField;
        }
        set {
            this.pROGRAM_NUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string POST_POS {
        get {
            return this.pOST_POSField;
        }
        set {
            this.pOST_POSField = value;
        }
    }
    
    /// <remarks/>
    public decimal CLAIM_PRICE {
        get {
            return this.cLAIM_PRICEField;
        }
        set {
            this.cLAIM_PRICEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string START_POSITION {
        get {
            return this.sTART_POSITIONField;
        }
        set {
            this.sTART_POSITIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("POINT_OF_CALL")]
    public POINT_OF_CALL[] POINT_OF_CALL {
        get {
            return this.pOINT_OF_CALLField;
        }
        set {
            this.pOINT_OF_CALLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string OFFICIAL_FIN {
        get {
            return this.oFFICIAL_FINField;
        }
        set {
            this.oFFICIAL_FINField = value;
        }
    }
    
    /// <remarks/>
    public string FINISH_TIME {
        get {
            return this.fINISH_TIMEField;
        }
        set {
            this.fINISH_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SPEED_RATING {
        get {
            return this.sPEED_RATINGField;
        }
        set {
            this.sPEED_RATINGField = value;
        }
    }
    
    /// <remarks/>
    public JOCKEY JOCKEY {
        get {
            return this.jOCKEYField;
        }
        set {
            this.jOCKEYField = value;
        }
    }
    
    /// <remarks/>
    public TRAINER TRAINER {
        get {
            return this.tRAINERField;
        }
        set {
            this.tRAINERField = value;
        }
    }
    
    /// <remarks/>
    public string OWNER {
        get {
            return this.oWNERField;
        }
        set {
            this.oWNERField = value;
        }
    }
    
    /// <remarks/>
    public string COMMENT {
        get {
            return this.cOMMENTField;
        }
        set {
            this.cOMMENTField = value;
        }
    }
    
    /// <remarks/>
    public WINNERS_DETAILS WINNERS_DETAILS {
        get {
            return this.wINNERS_DETAILSField;
        }
        set {
            this.wINNERS_DETAILSField = value;
        }
    }
    
    /// <remarks/>
    public decimal WIN_PAYOFF {
        get {
            return this.wIN_PAYOFFField;
        }
        set {
            this.wIN_PAYOFFField = value;
        }
    }
    
    /// <remarks/>
    public decimal PLACE_PAYOFF {
        get {
            return this.pLACE_PAYOFFField;
        }
        set {
            this.pLACE_PAYOFFField = value;
        }
    }
    
    /// <remarks/>
    public decimal SHOW_PAYOFF {
        get {
            return this.sHOW_PAYOFFField;
        }
        set {
            this.sHOW_PAYOFFField = value;
        }
    }
    
    /// <remarks/>
    public decimal SHOW_PAYOFF2 {
        get {
            return this.sHOW_PAYOFF2Field;
        }
        set {
            this.sHOW_PAYOFF2Field = value;
        }
    }
    
    /// <remarks/>
    public string AXCISKEY {
        get {
            return this.aXCISKEYField;
        }
        set {
            this.aXCISKEYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class LAST_PP {
    
    private TRACK tRACKField;
    
    private System.DateTime rACE_DATEField;
    
    private string rACE_NUMBERField;
    
    private string oFL_FINISHField;
    
    /// <remarks/>
    public TRACK TRACK {
        get {
            return this.tRACKField;
        }
        set {
            this.tRACKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime RACE_DATE {
        get {
            return this.rACE_DATEField;
        }
        set {
            this.rACE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string RACE_NUMBER {
        get {
            return this.rACE_NUMBERField;
        }
        set {
            this.rACE_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string OFL_FINISH {
        get {
            return this.oFL_FINISHField;
        }
        set {
            this.oFL_FINISHField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SEX {
    
    private string cODEField;
    
    private string dESCRIPTIONField;
    
    /// <remarks/>
    public string CODE {
        get {
            return this.cODEField;
        }
        set {
            this.cODEField = value;
        }
    }
    
    /// <remarks/>
    public string DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class POINT_OF_CALL {
    
    private string pOSITIONField;
    
    private decimal lENGTHSField;
    
    private string wHICHField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string POSITION {
        get {
            return this.pOSITIONField;
        }
        set {
            this.pOSITIONField = value;
        }
    }
    
    /// <remarks/>
    public decimal LENGTHS {
        get {
            return this.lENGTHSField;
        }
        set {
            this.lENGTHSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string WHICH {
        get {
            return this.wHICHField;
        }
        set {
            this.wHICHField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class JOCKEY {
    
    private string fIRST_NAMEField;
    
    private string mIDDLE_NAMEField;
    
    private string lAST_NAMEField;
    
    private string sUFFIXField;
    
    private string kEYField;
    
    private string tYPEField;
    
    /// <remarks/>
    public string FIRST_NAME {
        get {
            return this.fIRST_NAMEField;
        }
        set {
            this.fIRST_NAMEField = value;
        }
    }
    
    /// <remarks/>
    public string MIDDLE_NAME {
        get {
            return this.mIDDLE_NAMEField;
        }
        set {
            this.mIDDLE_NAMEField = value;
        }
    }
    
    /// <remarks/>
    public string LAST_NAME {
        get {
            return this.lAST_NAMEField;
        }
        set {
            this.lAST_NAMEField = value;
        }
    }
    
    /// <remarks/>
    public string SUFFIX {
        get {
            return this.sUFFIXField;
        }
        set {
            this.sUFFIXField = value;
        }
    }
    
    /// <remarks/>
    public string KEY {
        get {
            return this.kEYField;
        }
        set {
            this.kEYField = value;
        }
    }
    
    /// <remarks/>
    public string TYPE {
        get {
            return this.tYPEField;
        }
        set {
            this.tYPEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class WINNERS_DETAILS {
    
    private COLOR cOLORField;
    
    private string sIREField;
    
    private string dAMField;
    
    private string dAM_SIREField;
    
    private string bREEDERField;
    
    private BRED_LOCATION bRED_LOCATIONField;
    
    /// <remarks/>
    public COLOR COLOR {
        get {
            return this.cOLORField;
        }
        set {
            this.cOLORField = value;
        }
    }
    
    /// <remarks/>
    public string SIRE {
        get {
            return this.sIREField;
        }
        set {
            this.sIREField = value;
        }
    }
    
    /// <remarks/>
    public string DAM {
        get {
            return this.dAMField;
        }
        set {
            this.dAMField = value;
        }
    }
    
    /// <remarks/>
    public string DAM_SIRE {
        get {
            return this.dAM_SIREField;
        }
        set {
            this.dAM_SIREField = value;
        }
    }
    
    /// <remarks/>
    public string BREEDER {
        get {
            return this.bREEDERField;
        }
        set {
            this.bREEDERField = value;
        }
    }
    
    /// <remarks/>
    public BRED_LOCATION BRED_LOCATION {
        get {
            return this.bRED_LOCATIONField;
        }
        set {
            this.bRED_LOCATIONField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class COLOR {
    
    private string cODEField;
    
    private string dESCRIPTIONField;
    
    /// <remarks/>
    public string CODE {
        get {
            return this.cODEField;
        }
        set {
            this.cODEField = value;
        }
    }
    
    /// <remarks/>
    public string DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BRED_LOCATION {
    
    private string cODEField;
    
    private string dESCRIPTIONField;
    
    /// <remarks/>
    public string CODE {
        get {
            return this.cODEField;
        }
        set {
            this.cODEField = value;
        }
    }
    
    /// <remarks/>
    public string DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SCRATCH {
    
    private string nAMEField;
    
    private string bREEDField;
    
    private string rEASONField;
    
    private LAST_PP lAST_PPField;
    
    /// <remarks/>
    public string NAME {
        get {
            return this.nAMEField;
        }
        set {
            this.nAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string BREED {
        get {
            return this.bREEDField;
        }
        set {
            this.bREEDField = value;
        }
    }
    
    /// <remarks/>
    public string REASON {
        get {
            return this.rEASONField;
        }
        set {
            this.rEASONField = value;
        }
    }
    
    /// <remarks/>
    public LAST_PP LAST_PP {
        get {
            return this.lAST_PPField;
        }
        set {
            this.lAST_PPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EXOTIC_WAGERS {
    
    private WAGER[] wAGERField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WAGER")]
    public WAGER[] WAGER {
        get {
            return this.wAGERField;
        }
        set {
            this.wAGERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CLAIMED {
    
    private CLAIM[] cLAIMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CLAIM")]
    public CLAIM[] CLAIM {
        get {
            return this.cLAIMField;
        }
        set {
            this.cLAIMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class VOIDED_CLAIMS {
    
    private VOIDED_CLAIM[] vOIDED_CLAIMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VOIDED_CLAIM")]
    public VOIDED_CLAIM[] VOIDED_CLAIM {
        get {
            return this.vOIDED_CLAIMField;
        }
        set {
            this.vOIDED_CLAIMField = value;
        }
    }
}
