//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class data {
    
    private racedata[] racedataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("racedata")]
    public racedata[] racedata {
        get {
            return this.racedataField;
        }
        set {
            this.racedataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class racedata {
    
    private string raceField;
    
    private string todays_clsField;
    
    private decimal distanceField;
    
    private string dist_unitField;
    
    private string course_idField;
    
    private string surfaceField;
    
    private string stkorclmField;
    
    private string purseField;
    
    private string claimamtField;
    
    private string age_restrField;
    
    private string bet_optField;
    
    private string trackField;
    
    private string send_trackField;
    
    private string raceordField;
    
    private decimal partimField;
    
    private string dist_dispField;
    
    private string breed_typeField;
    
    private string post_timeField;
    
    private string race_dateField;
    
    private string race_textField;
    
    private string stk_clm_mdField;
    
    private string countryField;
    
    private horsedata[] horsedataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string race {
        get {
            return this.raceField;
        }
        set {
            this.raceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string todays_cls {
        get {
            return this.todays_clsField;
        }
        set {
            this.todays_clsField = value;
        }
    }
    
    /// <remarks/>
    public decimal distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string dist_unit {
        get {
            return this.dist_unitField;
        }
        set {
            this.dist_unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string course_id {
        get {
            return this.course_idField;
        }
        set {
            this.course_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string surface {
        get {
            return this.surfaceField;
        }
        set {
            this.surfaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string stkorclm {
        get {
            return this.stkorclmField;
        }
        set {
            this.stkorclmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string purse {
        get {
            return this.purseField;
        }
        set {
            this.purseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string claimamt {
        get {
            return this.claimamtField;
        }
        set {
            this.claimamtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
    public string age_restr {
        get {
            return this.age_restrField;
        }
        set {
            this.age_restrField = value;
        }
    }
    
    /// <remarks/>
    public string bet_opt {
        get {
            return this.bet_optField;
        }
        set {
            this.bet_optField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string track {
        get {
            return this.trackField;
        }
        set {
            this.trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string send_track {
        get {
            return this.send_trackField;
        }
        set {
            this.send_trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string raceord {
        get {
            return this.raceordField;
        }
        set {
            this.raceordField = value;
        }
    }
    
    /// <remarks/>
    public decimal partim {
        get {
            return this.partimField;
        }
        set {
            this.partimField = value;
        }
    }
    
    /// <remarks/>
    public string dist_disp {
        get {
            return this.dist_dispField;
        }
        set {
            this.dist_dispField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string breed_type {
        get {
            return this.breed_typeField;
        }
        set {
            this.breed_typeField = value;
        }
    }
    
    /// <remarks/>
    public string post_time {
        get {
            return this.post_timeField;
        }
        set {
            this.post_timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string race_date {
        get {
            return this.race_dateField;
        }
        set {
            this.race_dateField = value;
        }
    }
    
    /// <remarks/>
    public string race_text {
        get {
            return this.race_textField;
        }
        set {
            this.race_textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string stk_clm_md {
        get {
            return this.stk_clm_mdField;
        }
        set {
            this.stk_clm_mdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("horsedata")]
    public horsedata[] horsedata {
        get {
            return this.horsedataField;
        }
        set {
            this.horsedataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class horsedata {
    
    private string horse_nameField;
    
    private string owner_nameField;
    
    private string programField;
    
    private string ppField;
    
    private string todays_clsField;
    
    private string avg_spd_sdField;
    
    private string ave_cl_sdField;
    
    private string hi_spd_sdField;
    
    private string foal_dateField;
    
    private decimal pstyerlField;
    
    private decimal pstymidField;
    
    private decimal pstyfinField;
    
    private string pstynumField;
    
    private string pstyoffField;
    
    private decimal psprstyerlField;
    
    private decimal psprstymidField;
    
    private decimal psprstyfinField;
    
    private string psprstynumField;
    
    private string psprstyoffField;
    
    private decimal prtestyerlField;
    
    private decimal prtestymidField;
    
    private decimal prtestyfinField;
    
    private string prtestynumField;
    
    private string prtestyoffField;
    
    private decimal pallstyerlField;
    
    private decimal pallstymidField;
    
    private decimal pallstyfinField;
    
    private string pallstynumField;
    
    private string pallstyoffField;
    
    private decimal pfigerlField;
    
    private decimal pfigmidField;
    
    private decimal pfigfinField;
    
    private string pfignumField;
    
    private string pfigoffField;
    
    private decimal psprfigerlField;
    
    private decimal psprfigmidField;
    
    private decimal psprfigfinField;
    
    private string psprfignumField;
    
    private string psprfigoffField;
    
    private decimal prtefigerlField;
    
    private decimal prtefigmidField;
    
    private decimal prtefigfinField;
    
    private string prtefignumField;
    
    private string prtefigoffField;
    
    private decimal pallfigerlField;
    
    private decimal pallfigmidField;
    
    private decimal pallfigfinField;
    
    private string pallfignumField;
    
    private string pallfigoffField;
    
    private string tmmarkField;
    
    private decimal av_pur_valField;
    
    private string weightField;
    
    private string wght_shiftField;
    
    private string cldateField;
    
    private string priceField;
    
    private string bought_frField;
    
    private string sexField;
    
    private decimal powerField;
    
    private string medField;
    
    private string equipField;
    
    private string morn_oddsField;
    
    private string breederField;
    
    private string wh_foaledField;
    
    private string ae_flagField;
    
    private string colorField;
    
    private string power_symbField;
    
    private string horse_commField;
    
    private string breed_typeField;
    
    private string lst_salenaField;
    
    private decimal lst_saleprField;
    
    private string lst_saledaField;
    
    private string claimpriceField;
    
    private string avgspdField;
    
    private string avgclsField;
    
    private string apprweightField;
    
    private string axciskeyField;
    
    private stat[] stats_dataField;
    
    private sire sireField;
    
    private dam damField;
    
    private jockey jockeyField;
    
    private trainer trainerField;
    
    private workoutdata[] workoutdataField;
    
    private ppdata[] ppdataField;
    
    /// <remarks/>
    public string horse_name {
        get {
            return this.horse_nameField;
        }
        set {
            this.horse_nameField = value;
        }
    }
    
    /// <remarks/>
    public string owner_name {
        get {
            return this.owner_nameField;
        }
        set {
            this.owner_nameField = value;
        }
    }
    
    /// <remarks/>
    public string program {
        get {
            return this.programField;
        }
        set {
            this.programField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pp {
        get {
            return this.ppField;
        }
        set {
            this.ppField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string todays_cls {
        get {
            return this.todays_clsField;
        }
        set {
            this.todays_clsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
    public string avg_spd_sd {
        get {
            return this.avg_spd_sdField;
        }
        set {
            this.avg_spd_sdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
    public string ave_cl_sd {
        get {
            return this.ave_cl_sdField;
        }
        set {
            this.ave_cl_sdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
    public string hi_spd_sd {
        get {
            return this.hi_spd_sdField;
        }
        set {
            this.hi_spd_sdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string foal_date {
        get {
            return this.foal_dateField;
        }
        set {
            this.foal_dateField = value;
        }
    }
    
    /// <remarks/>
    public decimal pstyerl {
        get {
            return this.pstyerlField;
        }
        set {
            this.pstyerlField = value;
        }
    }
    
    /// <remarks/>
    public decimal pstymid {
        get {
            return this.pstymidField;
        }
        set {
            this.pstymidField = value;
        }
    }
    
    /// <remarks/>
    public decimal pstyfin {
        get {
            return this.pstyfinField;
        }
        set {
            this.pstyfinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pstynum {
        get {
            return this.pstynumField;
        }
        set {
            this.pstynumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pstyoff {
        get {
            return this.pstyoffField;
        }
        set {
            this.pstyoffField = value;
        }
    }
    
    /// <remarks/>
    public decimal psprstyerl {
        get {
            return this.psprstyerlField;
        }
        set {
            this.psprstyerlField = value;
        }
    }
    
    /// <remarks/>
    public decimal psprstymid {
        get {
            return this.psprstymidField;
        }
        set {
            this.psprstymidField = value;
        }
    }
    
    /// <remarks/>
    public decimal psprstyfin {
        get {
            return this.psprstyfinField;
        }
        set {
            this.psprstyfinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string psprstynum {
        get {
            return this.psprstynumField;
        }
        set {
            this.psprstynumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string psprstyoff {
        get {
            return this.psprstyoffField;
        }
        set {
            this.psprstyoffField = value;
        }
    }
    
    /// <remarks/>
    public decimal prtestyerl {
        get {
            return this.prtestyerlField;
        }
        set {
            this.prtestyerlField = value;
        }
    }
    
    /// <remarks/>
    public decimal prtestymid {
        get {
            return this.prtestymidField;
        }
        set {
            this.prtestymidField = value;
        }
    }
    
    /// <remarks/>
    public decimal prtestyfin {
        get {
            return this.prtestyfinField;
        }
        set {
            this.prtestyfinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string prtestynum {
        get {
            return this.prtestynumField;
        }
        set {
            this.prtestynumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string prtestyoff {
        get {
            return this.prtestyoffField;
        }
        set {
            this.prtestyoffField = value;
        }
    }
    
    /// <remarks/>
    public decimal pallstyerl {
        get {
            return this.pallstyerlField;
        }
        set {
            this.pallstyerlField = value;
        }
    }
    
    /// <remarks/>
    public decimal pallstymid {
        get {
            return this.pallstymidField;
        }
        set {
            this.pallstymidField = value;
        }
    }
    
    /// <remarks/>
    public decimal pallstyfin {
        get {
            return this.pallstyfinField;
        }
        set {
            this.pallstyfinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pallstynum {
        get {
            return this.pallstynumField;
        }
        set {
            this.pallstynumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pallstyoff {
        get {
            return this.pallstyoffField;
        }
        set {
            this.pallstyoffField = value;
        }
    }
    
    /// <remarks/>
    public decimal pfigerl {
        get {
            return this.pfigerlField;
        }
        set {
            this.pfigerlField = value;
        }
    }
    
    /// <remarks/>
    public decimal pfigmid {
        get {
            return this.pfigmidField;
        }
        set {
            this.pfigmidField = value;
        }
    }
    
    /// <remarks/>
    public decimal pfigfin {
        get {
            return this.pfigfinField;
        }
        set {
            this.pfigfinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pfignum {
        get {
            return this.pfignumField;
        }
        set {
            this.pfignumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pfigoff {
        get {
            return this.pfigoffField;
        }
        set {
            this.pfigoffField = value;
        }
    }
    
    /// <remarks/>
    public decimal psprfigerl {
        get {
            return this.psprfigerlField;
        }
        set {
            this.psprfigerlField = value;
        }
    }
    
    /// <remarks/>
    public decimal psprfigmid {
        get {
            return this.psprfigmidField;
        }
        set {
            this.psprfigmidField = value;
        }
    }
    
    /// <remarks/>
    public decimal psprfigfin {
        get {
            return this.psprfigfinField;
        }
        set {
            this.psprfigfinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string psprfignum {
        get {
            return this.psprfignumField;
        }
        set {
            this.psprfignumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string psprfigoff {
        get {
            return this.psprfigoffField;
        }
        set {
            this.psprfigoffField = value;
        }
    }
    
    /// <remarks/>
    public decimal prtefigerl {
        get {
            return this.prtefigerlField;
        }
        set {
            this.prtefigerlField = value;
        }
    }
    
    /// <remarks/>
    public decimal prtefigmid {
        get {
            return this.prtefigmidField;
        }
        set {
            this.prtefigmidField = value;
        }
    }
    
    /// <remarks/>
    public decimal prtefigfin {
        get {
            return this.prtefigfinField;
        }
        set {
            this.prtefigfinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string prtefignum {
        get {
            return this.prtefignumField;
        }
        set {
            this.prtefignumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string prtefigoff {
        get {
            return this.prtefigoffField;
        }
        set {
            this.prtefigoffField = value;
        }
    }
    
    /// <remarks/>
    public decimal pallfigerl {
        get {
            return this.pallfigerlField;
        }
        set {
            this.pallfigerlField = value;
        }
    }
    
    /// <remarks/>
    public decimal pallfigmid {
        get {
            return this.pallfigmidField;
        }
        set {
            this.pallfigmidField = value;
        }
    }
    
    /// <remarks/>
    public decimal pallfigfin {
        get {
            return this.pallfigfinField;
        }
        set {
            this.pallfigfinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pallfignum {
        get {
            return this.pallfignumField;
        }
        set {
            this.pallfignumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pallfigoff {
        get {
            return this.pallfigoffField;
        }
        set {
            this.pallfigoffField = value;
        }
    }
    
    /// <remarks/>
    public string tmmark {
        get {
            return this.tmmarkField;
        }
        set {
            this.tmmarkField = value;
        }
    }
    
    /// <remarks/>
    public decimal av_pur_val {
        get {
            return this.av_pur_valField;
        }
        set {
            this.av_pur_valField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string wght_shift {
        get {
            return this.wght_shiftField;
        }
        set {
            this.wght_shiftField = value;
        }
    }
    
    /// <remarks/>
    public string cldate {
        get {
            return this.cldateField;
        }
        set {
            this.cldateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public string bought_fr {
        get {
            return this.bought_frField;
        }
        set {
            this.bought_frField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string sex {
        get {
            return this.sexField;
        }
        set {
            this.sexField = value;
        }
    }
    
    /// <remarks/>
    public decimal power {
        get {
            return this.powerField;
        }
        set {
            this.powerField = value;
        }
    }
    
    /// <remarks/>
    public string med {
        get {
            return this.medField;
        }
        set {
            this.medField = value;
        }
    }
    
    /// <remarks/>
    public string equip {
        get {
            return this.equipField;
        }
        set {
            this.equipField = value;
        }
    }
    
    /// <remarks/>
    public string morn_odds {
        get {
            return this.morn_oddsField;
        }
        set {
            this.morn_oddsField = value;
        }
    }
    
    /// <remarks/>
    public string breeder {
        get {
            return this.breederField;
        }
        set {
            this.breederField = value;
        }
    }
    
    /// <remarks/>
    public string wh_foaled {
        get {
            return this.wh_foaledField;
        }
        set {
            this.wh_foaledField = value;
        }
    }
    
    /// <remarks/>
    public string ae_flag {
        get {
            return this.ae_flagField;
        }
        set {
            this.ae_flagField = value;
        }
    }
    
    /// <remarks/>
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    public string power_symb {
        get {
            return this.power_symbField;
        }
        set {
            this.power_symbField = value;
        }
    }
    
    /// <remarks/>
    public string horse_comm {
        get {
            return this.horse_commField;
        }
        set {
            this.horse_commField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string breed_type {
        get {
            return this.breed_typeField;
        }
        set {
            this.breed_typeField = value;
        }
    }
    
    /// <remarks/>
    public string lst_salena {
        get {
            return this.lst_salenaField;
        }
        set {
            this.lst_salenaField = value;
        }
    }
    
    /// <remarks/>
    public decimal lst_salepr {
        get {
            return this.lst_saleprField;
        }
        set {
            this.lst_saleprField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string lst_saleda {
        get {
            return this.lst_saledaField;
        }
        set {
            this.lst_saledaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string claimprice {
        get {
            return this.claimpriceField;
        }
        set {
            this.claimpriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string avgspd {
        get {
            return this.avgspdField;
        }
        set {
            this.avgspdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string avgcls {
        get {
            return this.avgclsField;
        }
        set {
            this.avgclsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string apprweight {
        get {
            return this.apprweightField;
        }
        set {
            this.apprweightField = value;
        }
    }
    
    /// <remarks/>
    public string axciskey {
        get {
            return this.axciskeyField;
        }
        set {
            this.axciskeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("stat", IsNullable=false)]
    public stat[] stats_data {
        get {
            return this.stats_dataField;
        }
        set {
            this.stats_dataField = value;
        }
    }
    
    /// <remarks/>
    public sire sire {
        get {
            return this.sireField;
        }
        set {
            this.sireField = value;
        }
    }
    
    /// <remarks/>
    public dam dam {
        get {
            return this.damField;
        }
        set {
            this.damField = value;
        }
    }
    
    /// <remarks/>
    public jockey jockey {
        get {
            return this.jockeyField;
        }
        set {
            this.jockeyField = value;
        }
    }
    
    /// <remarks/>
    public trainer trainer {
        get {
            return this.trainerField;
        }
        set {
            this.trainerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("workoutdata")]
    public workoutdata[] workoutdata {
        get {
            return this.workoutdataField;
        }
        set {
            this.workoutdataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ppdata")]
    public ppdata[] ppdata {
        get {
            return this.ppdataField;
        }
        set {
            this.ppdataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class stat {
    
    private string startsField;
    
    private string winsField;
    
    private string placesField;
    
    private string showsField;
    
    private string earningsField;
    
    private decimal paidField;
    
    private string roiField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string starts {
        get {
            return this.startsField;
        }
        set {
            this.startsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string wins {
        get {
            return this.winsField;
        }
        set {
            this.winsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string places {
        get {
            return this.placesField;
        }
        set {
            this.placesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string shows {
        get {
            return this.showsField;
        }
        set {
            this.showsField = value;
        }
    }
    
    /// <remarks/>
    public string earnings {
        get {
            return this.earningsField;
        }
        set {
            this.earningsField = value;
        }
    }
    
    /// <remarks/>
    public decimal paid {
        get {
            return this.paidField;
        }
        set {
            this.paidField = value;
        }
    }
    
    /// <remarks/>
    public string roi {
        get {
            return this.roiField;
        }
        set {
            this.roiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class sire {
    
    private string stat_breedField;
    
    private string sirenameField;
    
    private string tmmarkField;
    
    private string stud_feeField;
    
    private stat[] stats_dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string stat_breed {
        get {
            return this.stat_breedField;
        }
        set {
            this.stat_breedField = value;
        }
    }
    
    /// <remarks/>
    public string sirename {
        get {
            return this.sirenameField;
        }
        set {
            this.sirenameField = value;
        }
    }
    
    /// <remarks/>
    public string tmmark {
        get {
            return this.tmmarkField;
        }
        set {
            this.tmmarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string stud_fee {
        get {
            return this.stud_feeField;
        }
        set {
            this.stud_feeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("stat", IsNullable=false)]
    public stat[] stats_data {
        get {
            return this.stats_dataField;
        }
        set {
            this.stats_dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class dam {
    
    private string stat_breedField;
    
    private string damnameField;
    
    private string damsireField;
    
    private stat[] stats_dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string stat_breed {
        get {
            return this.stat_breedField;
        }
        set {
            this.stat_breedField = value;
        }
    }
    
    /// <remarks/>
    public string damname {
        get {
            return this.damnameField;
        }
        set {
            this.damnameField = value;
        }
    }
    
    /// <remarks/>
    public string damsire {
        get {
            return this.damsireField;
        }
        set {
            this.damsireField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("stat", IsNullable=false)]
    public stat[] stats_data {
        get {
            return this.stats_dataField;
        }
        set {
            this.stats_dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class jockey {
    
    private string stat_breedField;
    
    private string jock_dispField;
    
    private string jock_keyField;
    
    private string j_typeField;
    
    private stat[] stats_dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string stat_breed {
        get {
            return this.stat_breedField;
        }
        set {
            this.stat_breedField = value;
        }
    }
    
    /// <remarks/>
    public string jock_disp {
        get {
            return this.jock_dispField;
        }
        set {
            this.jock_dispField = value;
        }
    }
    
    /// <remarks/>
    public string jock_key {
        get {
            return this.jock_keyField;
        }
        set {
            this.jock_keyField = value;
        }
    }
    
    /// <remarks/>
    public string j_type {
        get {
            return this.j_typeField;
        }
        set {
            this.j_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("stat", IsNullable=false)]
    public stat[] stats_data {
        get {
            return this.stats_dataField;
        }
        set {
            this.stats_dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class trainer {
    
    private string stat_breedField;
    
    private string tran_dispField;
    
    private string train_keyField;
    
    private string t_typeField;
    
    private stat[] stats_dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string stat_breed {
        get {
            return this.stat_breedField;
        }
        set {
            this.stat_breedField = value;
        }
    }
    
    /// <remarks/>
    public string tran_disp {
        get {
            return this.tran_dispField;
        }
        set {
            this.tran_dispField = value;
        }
    }
    
    /// <remarks/>
    public string train_key {
        get {
            return this.train_keyField;
        }
        set {
            this.train_keyField = value;
        }
    }
    
    /// <remarks/>
    public string t_type {
        get {
            return this.t_typeField;
        }
        set {
            this.t_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("stat", IsNullable=false)]
    public stat[] stats_data {
        get {
            return this.stats_dataField;
        }
        set {
            this.stats_dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class workoutdata {
    
    private string worknumField;
    
    private string days_backField;
    
    private string worktextField;
    
    private string rankingField;
    
    private string rank_groupField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string worknum {
        get {
            return this.worknumField;
        }
        set {
            this.worknumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string days_back {
        get {
            return this.days_backField;
        }
        set {
            this.days_backField = value;
        }
    }
    
    /// <remarks/>
    public string worktext {
        get {
            return this.worktextField;
        }
        set {
            this.worktextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ranking {
        get {
            return this.rankingField;
        }
        set {
            this.rankingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string rank_group {
        get {
            return this.rank_groupField;
        }
        set {
            this.rank_groupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ppdata {
    
    private string racedateField;
    
    private string trackcodeField;
    
    private string tracknameField;
    
    private string racenumberField;
    
    private string racebreedField;
    
    private string countryField;
    
    private string racetypeField;
    
    private string raceclassField;
    
    private string claimpriceField;
    
    private string purseField;
    
    private string classratinField;
    
    private string trackcondiField;
    
    private decimal distanceField;
    
    private string disttypeField;
    
    private string aboutdistField;
    
    private string courseidField;
    
    private string surfaceField;
    
    private string pulledofftField;
    
    private string winddirectField;
    
    private string windspeedField;
    
    private string trackvariaField;
    
    private string sealedtracField;
    
    private string racegradeField;
    
    private string agerestricField;
    
    private string sexrestricField;
    
    private string statebredrField;
    
    private string abbrevcondField;
    
    private string postpositiField;
    
    private string favoriteField;
    
    private string weightcarrField;
    
    private string jockfirstField;
    
    private string jockmiddleField;
    
    private string jocklastField;
    
    private string jocksuffixField;
    
    private string jockdispField;
    
    private string equipmentField;
    
    private string medicationField;
    
    private string fieldsizeField;
    
    private decimal posttimeodField;
    
    private string shortcommeField;
    
    private string longcommenField;
    
    private string gatebreakField;
    
    private string position1Field;
    
    private decimal lenback1Field;
    
    private decimal horsetime1Field;
    
    private decimal leadertimeField;
    
    private string pacefigureField;
    
    private string position2Field;
    
    private decimal lenback2Field;
    
    private decimal horsetime2Field;
    
    private decimal leadertim2Field;
    
    private string pacefigur2Field;
    
    private string positionstField;
    
    private decimal lenbackstrField;
    
    private decimal horsetimesField;
    
    private decimal leadertim3Field;
    
    private string dqindicatoField;
    
    private string positionfiField;
    
    private decimal lenbackfinField;
    
    private decimal horsetimefField;
    
    private decimal leadertim4Field;
    
    private string speedfigurField;
    
    private decimal turffigureField;
    
    private string winnersspeField;
    
    private string foreignspeField;
    
    private string horseclaimField;
    
    private string biasstyleField;
    
    private string biaspathField;
    
    private string complinehoField;
    
    private decimal complineleField;
    
    private string complineweField;
    
    private string complinedqField;
    
    private string complineh2Field;
    
    private decimal complinel2Field;
    
    private string complinew2Field;
    
    private string complined2Field;
    
    private string complineh3Field;
    
    private decimal complinel3Field;
    
    private string complinew3Field;
    
    private string complined3Field;
    
    private string linebeforeField;
    
    private string lineafterField;
    
    private string domesticppField;
    
    private string oflfinishField;
    
    private string runup_distField;
    
    private string rail_distField;
    
    private string apprweightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string racedate {
        get {
            return this.racedateField;
        }
        set {
            this.racedateField = value;
        }
    }
    
    /// <remarks/>
    public string trackcode {
        get {
            return this.trackcodeField;
        }
        set {
            this.trackcodeField = value;
        }
    }
    
    /// <remarks/>
    public string trackname {
        get {
            return this.tracknameField;
        }
        set {
            this.tracknameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string racenumber {
        get {
            return this.racenumberField;
        }
        set {
            this.racenumberField = value;
        }
    }
    
    /// <remarks/>
    public string racebreed {
        get {
            return this.racebreedField;
        }
        set {
            this.racebreedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public string racetype {
        get {
            return this.racetypeField;
        }
        set {
            this.racetypeField = value;
        }
    }
    
    /// <remarks/>
    public string raceclass {
        get {
            return this.raceclassField;
        }
        set {
            this.raceclassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string claimprice {
        get {
            return this.claimpriceField;
        }
        set {
            this.claimpriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string purse {
        get {
            return this.purseField;
        }
        set {
            this.purseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string classratin {
        get {
            return this.classratinField;
        }
        set {
            this.classratinField = value;
        }
    }
    
    /// <remarks/>
    public string trackcondi {
        get {
            return this.trackcondiField;
        }
        set {
            this.trackcondiField = value;
        }
    }
    
    /// <remarks/>
    public decimal distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    public string disttype {
        get {
            return this.disttypeField;
        }
        set {
            this.disttypeField = value;
        }
    }
    
    /// <remarks/>
    public string aboutdist {
        get {
            return this.aboutdistField;
        }
        set {
            this.aboutdistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string courseid {
        get {
            return this.courseidField;
        }
        set {
            this.courseidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
    public string surface {
        get {
            return this.surfaceField;
        }
        set {
            this.surfaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pulledofft {
        get {
            return this.pulledofftField;
        }
        set {
            this.pulledofftField = value;
        }
    }
    
    /// <remarks/>
    public string winddirect {
        get {
            return this.winddirectField;
        }
        set {
            this.winddirectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string windspeed {
        get {
            return this.windspeedField;
        }
        set {
            this.windspeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string trackvaria {
        get {
            return this.trackvariaField;
        }
        set {
            this.trackvariaField = value;
        }
    }
    
    /// <remarks/>
    public string sealedtrac {
        get {
            return this.sealedtracField;
        }
        set {
            this.sealedtracField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string racegrade {
        get {
            return this.racegradeField;
        }
        set {
            this.racegradeField = value;
        }
    }
    
    /// <remarks/>
    public string agerestric {
        get {
            return this.agerestricField;
        }
        set {
            this.agerestricField = value;
        }
    }
    
    /// <remarks/>
    public string sexrestric {
        get {
            return this.sexrestricField;
        }
        set {
            this.sexrestricField = value;
        }
    }
    
    /// <remarks/>
    public string statebredr {
        get {
            return this.statebredrField;
        }
        set {
            this.statebredrField = value;
        }
    }
    
    /// <remarks/>
    public string abbrevcond {
        get {
            return this.abbrevcondField;
        }
        set {
            this.abbrevcondField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string postpositi {
        get {
            return this.postpositiField;
        }
        set {
            this.postpositiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string favorite {
        get {
            return this.favoriteField;
        }
        set {
            this.favoriteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string weightcarr {
        get {
            return this.weightcarrField;
        }
        set {
            this.weightcarrField = value;
        }
    }
    
    /// <remarks/>
    public string jockfirst {
        get {
            return this.jockfirstField;
        }
        set {
            this.jockfirstField = value;
        }
    }
    
    /// <remarks/>
    public string jockmiddle {
        get {
            return this.jockmiddleField;
        }
        set {
            this.jockmiddleField = value;
        }
    }
    
    /// <remarks/>
    public string jocklast {
        get {
            return this.jocklastField;
        }
        set {
            this.jocklastField = value;
        }
    }
    
    /// <remarks/>
    public string jocksuffix {
        get {
            return this.jocksuffixField;
        }
        set {
            this.jocksuffixField = value;
        }
    }
    
    /// <remarks/>
    public string jockdisp {
        get {
            return this.jockdispField;
        }
        set {
            this.jockdispField = value;
        }
    }
    
    /// <remarks/>
    public string equipment {
        get {
            return this.equipmentField;
        }
        set {
            this.equipmentField = value;
        }
    }
    
    /// <remarks/>
    public string medication {
        get {
            return this.medicationField;
        }
        set {
            this.medicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string fieldsize {
        get {
            return this.fieldsizeField;
        }
        set {
            this.fieldsizeField = value;
        }
    }
    
    /// <remarks/>
    public decimal posttimeod {
        get {
            return this.posttimeodField;
        }
        set {
            this.posttimeodField = value;
        }
    }
    
    /// <remarks/>
    public string shortcomme {
        get {
            return this.shortcommeField;
        }
        set {
            this.shortcommeField = value;
        }
    }
    
    /// <remarks/>
    public string longcommen {
        get {
            return this.longcommenField;
        }
        set {
            this.longcommenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string gatebreak {
        get {
            return this.gatebreakField;
        }
        set {
            this.gatebreakField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string position1 {
        get {
            return this.position1Field;
        }
        set {
            this.position1Field = value;
        }
    }
    
    /// <remarks/>
    public decimal lenback1 {
        get {
            return this.lenback1Field;
        }
        set {
            this.lenback1Field = value;
        }
    }
    
    /// <remarks/>
    public decimal horsetime1 {
        get {
            return this.horsetime1Field;
        }
        set {
            this.horsetime1Field = value;
        }
    }
    
    /// <remarks/>
    public decimal leadertime {
        get {
            return this.leadertimeField;
        }
        set {
            this.leadertimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pacefigure {
        get {
            return this.pacefigureField;
        }
        set {
            this.pacefigureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string position2 {
        get {
            return this.position2Field;
        }
        set {
            this.position2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal lenback2 {
        get {
            return this.lenback2Field;
        }
        set {
            this.lenback2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal horsetime2 {
        get {
            return this.horsetime2Field;
        }
        set {
            this.horsetime2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal leadertim2 {
        get {
            return this.leadertim2Field;
        }
        set {
            this.leadertim2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string pacefigur2 {
        get {
            return this.pacefigur2Field;
        }
        set {
            this.pacefigur2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string positionst {
        get {
            return this.positionstField;
        }
        set {
            this.positionstField = value;
        }
    }
    
    /// <remarks/>
    public decimal lenbackstr {
        get {
            return this.lenbackstrField;
        }
        set {
            this.lenbackstrField = value;
        }
    }
    
    /// <remarks/>
    public decimal horsetimes {
        get {
            return this.horsetimesField;
        }
        set {
            this.horsetimesField = value;
        }
    }
    
    /// <remarks/>
    public decimal leadertim3 {
        get {
            return this.leadertim3Field;
        }
        set {
            this.leadertim3Field = value;
        }
    }
    
    /// <remarks/>
    public string dqindicato {
        get {
            return this.dqindicatoField;
        }
        set {
            this.dqindicatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string positionfi {
        get {
            return this.positionfiField;
        }
        set {
            this.positionfiField = value;
        }
    }
    
    /// <remarks/>
    public decimal lenbackfin {
        get {
            return this.lenbackfinField;
        }
        set {
            this.lenbackfinField = value;
        }
    }
    
    /// <remarks/>
    public decimal horsetimef {
        get {
            return this.horsetimefField;
        }
        set {
            this.horsetimefField = value;
        }
    }
    
    /// <remarks/>
    public decimal leadertim4 {
        get {
            return this.leadertim4Field;
        }
        set {
            this.leadertim4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string speedfigur {
        get {
            return this.speedfigurField;
        }
        set {
            this.speedfigurField = value;
        }
    }
    
    /// <remarks/>
    public decimal turffigure {
        get {
            return this.turffigureField;
        }
        set {
            this.turffigureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string winnersspe {
        get {
            return this.winnersspeField;
        }
        set {
            this.winnersspeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string foreignspe {
        get {
            return this.foreignspeField;
        }
        set {
            this.foreignspeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string horseclaim {
        get {
            return this.horseclaimField;
        }
        set {
            this.horseclaimField = value;
        }
    }
    
    /// <remarks/>
    public string biasstyle {
        get {
            return this.biasstyleField;
        }
        set {
            this.biasstyleField = value;
        }
    }
    
    /// <remarks/>
    public string biaspath {
        get {
            return this.biaspathField;
        }
        set {
            this.biaspathField = value;
        }
    }
    
    /// <remarks/>
    public string complineho {
        get {
            return this.complinehoField;
        }
        set {
            this.complinehoField = value;
        }
    }
    
    /// <remarks/>
    public decimal complinele {
        get {
            return this.complineleField;
        }
        set {
            this.complineleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string complinewe {
        get {
            return this.complineweField;
        }
        set {
            this.complineweField = value;
        }
    }
    
    /// <remarks/>
    public string complinedq {
        get {
            return this.complinedqField;
        }
        set {
            this.complinedqField = value;
        }
    }
    
    /// <remarks/>
    public string complineh2 {
        get {
            return this.complineh2Field;
        }
        set {
            this.complineh2Field = value;
        }
    }
    
    /// <remarks/>
    public decimal complinel2 {
        get {
            return this.complinel2Field;
        }
        set {
            this.complinel2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string complinew2 {
        get {
            return this.complinew2Field;
        }
        set {
            this.complinew2Field = value;
        }
    }
    
    /// <remarks/>
    public string complined2 {
        get {
            return this.complined2Field;
        }
        set {
            this.complined2Field = value;
        }
    }
    
    /// <remarks/>
    public string complineh3 {
        get {
            return this.complineh3Field;
        }
        set {
            this.complineh3Field = value;
        }
    }
    
    /// <remarks/>
    public decimal complinel3 {
        get {
            return this.complinel3Field;
        }
        set {
            this.complinel3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string complinew3 {
        get {
            return this.complinew3Field;
        }
        set {
            this.complinew3Field = value;
        }
    }
    
    /// <remarks/>
    public string complined3 {
        get {
            return this.complined3Field;
        }
        set {
            this.complined3Field = value;
        }
    }
    
    /// <remarks/>
    public string linebefore {
        get {
            return this.linebeforeField;
        }
        set {
            this.linebeforeField = value;
        }
    }
    
    /// <remarks/>
    public string lineafter {
        get {
            return this.lineafterField;
        }
        set {
            this.lineafterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string domesticpp {
        get {
            return this.domesticppField;
        }
        set {
            this.domesticppField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string oflfinish {
        get {
            return this.oflfinishField;
        }
        set {
            this.oflfinishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string runup_dist {
        get {
            return this.runup_distField;
        }
        set {
            this.runup_distField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string rail_dist {
        get {
            return this.rail_distField;
        }
        set {
            this.rail_distField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string apprweight {
        get {
            return this.apprweightField;
        }
        set {
            this.apprweightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class stats_data {
    
    private stat[] statField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stat")]
    public stat[] stat {
        get {
            return this.statField;
        }
        set {
            this.statField = value;
        }
    }
}
